version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: stg_products
    columns:
      - name: product_id
        tests: [not_null, unique]
      - name: is_active
        tests:
          - accepted_values:
              values: [true, false]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: status
        tests:
          - accepted_values:
              values: ['completed', 'cancelled']

  - name: stg_order_items
    columns:
      - name: order_item_id
        tests: [not_null, unique]
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
